site:
  title: Compose ur Pres Documentation
  url: https://KodeinKoders.github.io/CuP
  start_page: CuP::index.adoc
  robots: allow
content:
  sources:
    - url: ./
      start_path: docs
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
ui:
  bundle:
    url: https://github.com/kosi-libs/documentation-ui/raw/cup/build/ui-bundle-v1.2.2.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
urls:
  redirect_facility: 'static'
output:
  dir: build/site