= Getting Started with CuP

. Clone or create a new repository based on the https://github.com/kosi-libs/CuP-Presentation-Template[Cup template project].

. Edit `settings.gradle.kts`:
+
--
* Change the name of your project (which will define the package of the compose Res class).
--
+
.Example: `settings.gradle.kts`
[source, kotlin]
----
rootProject.name = "How-to-CuP"
----

. Edit `gradle/libs.versions.toml`:
+
--
* Select the plugins you want to activate in your presentation.
* Choose to compose your presentation with material 2 or material 3.
--
+
.Example: `build.gradle.kts`
[source, toml, subs="attributes,verbatim"]
----
[versions]
compose = "1.10.3"                      # https://github.com/JetBrains/compose-multiplatform/releases
emoji = "2.3.0"                         # https://github.com/kosi-libs/Emoji.kt/releases
kotlin = "2.3.20"                       # https://github.com/jetbrains/kotlin/releases
material3 = "1.10.0-alpha05"            # https://github.com/JetBrains/compose-multiplatform/releases
materialIcons = "1.7.3"                 # https://github.com/JetBrains/compose-multiplatform/releases

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
cup = { id = "net.kodein.cup" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
#compose-material2 = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
cup = { module = "net.kodein.cup:cup" }
cup-plugin-imageExport = { module = "net.kodein.cup:cup-plugin-image-export" }
cup-plugin-keyEvents = { module = "net.kodein.cup:cup-plugin-key-events" }
cup-plugin-laser = { module = "net.kodein.cup:cup-plugin-laser" }
cup-plugin-speakerWindow = { module = "net.kodein.cup:cup-plugin-speaker-window" }
#cup-widgets-material2 = { module = "net.kodein.cup:cup-widgets-material2" }
cup-widgets-material3 = { module = "net.kodein.cup:cup-widgets-material3" }
cup-widgets-sourceCode = { module = "net.kodein.cup:cup-widgets-source-code" }
#emoji-compose = { module = "org.kodein.emoji:emoji-compose-m2", version.ref = "emoji" }
emoji-compose = { module = "org.kodein.emoji:emoji-compose-m3", version.ref = "emoji" }

[bundles]
compose = [
    "compose-components-resources",
    "compose-foundation",
#    "compose-material2",
    "compose-material3",
    "compose-material-icons",
    "compose-runtime",
]
cup = [
    "cup",
    "cup-plugin-imageExport",
    "cup-plugin-keyEvents",
    "cup-plugin-laser",
    "cup-plugin-speakerWindow",
#    "cup-widgets-material2",
    "cup-widgets-material3",
    "cup-widgets-sourceCode",
]
----

. Edit `build.gradle.kts`:
+
--
* Choose if you want to export your presentation as a Web page (target web).
--
+
.Example: `build.gradle.kts`
[source, kotlin, subs="attributes,verbatim"]
----
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose)
    alias(libs.plugins.kotlin.plugin.compose)
    alias(libs.plugins.cup)
}

cup {
    targetDesktop()
    targetWeb()
}

kotlin {
    sourceSets.commonMain {
        dependencies {
            implementation(libs.bundles.compose)

            implementation(libs.bundles.cup)

            implementation(libs.emoji.compose)
        }
    }
}
----

. Edit `src/commonMain/kotlin/main.kt`:
+
--
* Change the title of your presentation.
* Configure the plugins you selected in your build config.
* Configure & apply your theme.
--
+
.Example: `src/commonMain/kotlin/main.kt`
[source, kotlin]
----
fun main() = cupApplication(title = "How to create a CuP!") {
    Presentation(
        slides = slides,
        configuration = {
            speakerWindow()
            laser()
            imageExport()
        }
    ) {
        MaterialTheme(colors = darkColors()) {
            Surface(Modifier.fillMaxSize()) {
                Slides()
            }
        }
    }
}

val slides = Slides(
    intro,
    whatIsCup,
    /*...*/
)
----

. *Write your slides!*
+
--
* Write each slide in `src/commonMain/kotlin/slides/`.
* Report them in order in `src/commonMain/kotlin/main.kt`.
--
+
.Example: `src/commonMain/kotlin/slides/intro.kt`
[source, kotlin]
----
val intro by Slide(
    stepCount = 2
) { step ->
    Image(
        painterResource(Res.drawable.cup),
        contentDescription = "Compose ur Pres",
        modifier = Modifier.size(96.dp).clip(CircleShape)
    )
    Text("Hello, friend!", fontSize = 32.sp)
    AnimatedVisibility(visible = step >= 1) {
        TextWithPlatformEmoji(
            styled { "Welcome to ${+b}Compose ur Pres${-b}! ${Emoji.Wink}" }
        )
    }
}
----

. Run your presentation:
* On desktop with the `./gradlew run` command.
* On the web (if you chose to target it) with the `./gradlew wasmJsBrowserRun` command.

. Export your presentation web page (if target web):
* If you are using Github Pages, run the `./gradlew distDoc` command that will generate the web page in the `doc/` directory.
* If you are using another system, run the `./gradlew wasmJsBrowserDistribution`  command that will generate the web page in the `build/dist/wasmJs/productionExecutable` directory.

. Change the `README.md` file to present your presentation ;)
