[versions]
buildConfig = "5.3.5"
compose = "1.6.10"
dokka = "1.9.20"
emoji = "2.0.1"
graalvm-js = "23.0.4"
gradle-pluginPublish = "1.2.1"
kotlin = "2.0.0"
kxSerialization = "1.7.0-RC"
markdown = "0.16.0"
mavenPublish = "0.28.0"
npm-ismobilejs = "1.1.1"
npm-highlightjs = "11.9.0"

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginPublish" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[libraries]
emojiCompose = { module = "org.kodein.emoji:emoji-compose", version.ref = "emoji" }
graalvm-js = { module = "org.graalvm.js:js", version.ref = "graalvm-js" }
kxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kxSerialization" }
markdown = { module = "com.mikepenz:multiplatform-markdown-renderer-m2", version.ref = "markdown" }
